run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs-use-default: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gocritic
    - godot
    - godox
    - gofmt
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - lll
    - loggercheck
    - misspell
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace

linters-settings:
  lll:
    line-length: 120

  gofmt:
    simplify: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

