package snowflake_test

import (
	"fmt"
	"log"
	"os"

	"github.com/spf13/viper"
	snowflake "github.com/teamlify-devx/idgen/snowflake"
)

// ExampleNewNode demonstrates how to create a new Snowflake ID generator node.
func ExampleNewNode() {
	// Configure using environment variables or config.yaml
	// For this example, we'll use manual configuration
	os.Setenv("SNOWFLAKE_NODE_TYPE", "manual")
	os.Setenv("SNOWFLAKE_NODE_ID", "1")

	node, err := snowflake.NewNode()
	if err != nil {
		log.Fatal(err)
	}

	// Use the node to generate IDs
	_ = node
}

// ExampleNode_Generate demonstrates ID generation.
func ExampleNode_Generate() {
	os.Setenv("SNOWFLAKE_NODE_TYPE", "single")

	node, err := snowflake.NewNode()
	if err != nil {
		log.Fatal(err)
	}

	// Generate a unique ID
	id, err := node.Generate()
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("Generated ID: %d\n", id)
}

// ExampleNode_Time demonstrates timestamp extraction.
func ExampleNode_Time() {
	os.Setenv("SNOWFLAKE_NODE_TYPE", "single")

	node, err := snowflake.NewNode()
	if err != nil {
		log.Fatal(err)
	}

	id, err := node.Generate()
	if err != nil {
		log.Fatal(err)
	}

	// Extract the timestamp from the ID
	ts := node.Time(id)
	fmt.Printf("ID was generated at: %v\n", ts)
}

// ExampleNode_NodeID demonstrates node ID extraction.
func ExampleNode_NodeID() {
	os.Setenv("SNOWFLAKE_NODE_TYPE", "manual")
	os.Setenv("SNOWFLAKE_NODE_ID", "5")

	node, err := snowflake.NewNode()
	if err != nil {
		log.Fatal(err)
	}

	id, err := node.Generate()
	if err != nil {
		log.Fatal(err)
	}

	// Extract the node ID from the generated ID
	nid := node.NodeID(id)
	fmt.Printf("This ID was generated by node: %d\n", nid)
}

// ExampleNode_Sequence demonstrates sequence extraction.
func ExampleNode_Sequence() {
	os.Setenv("SNOWFLAKE_NODE_TYPE", "single")

	node, err := snowflake.NewNode()
	if err != nil {
		log.Fatal(err)
	}

	id, err := node.Generate()
	if err != nil {
		log.Fatal(err)
	}

	// Extract the sequence number
	seq := node.Sequence(id)
	fmt.Printf("Sequence number: %d\n", seq)
}

// ExampleNewNode_withViper demonstrates using Viper for configuration.
func ExampleNewNode_withViper() {
	// Setup Viper to read from environment
	viper.SetEnvPrefix("SNOWFLAKE")
	viper.BindEnv("NODE_TYPE")
	viper.BindEnv("NODE_ID")
	viper.BindEnv("EPOCH")
	viper.BindEnv("NODE_BITS")
	viper.BindEnv("SEQUENCE_BITS")

	os.Setenv("SNOWFLAKE_NODE_TYPE", "manual")
	os.Setenv("SNOWFLAKE_NODE_ID", "1")

	node, err := snowflake.NewNode()
	if err != nil {
		log.Fatal(err)
	}

	_ = node
}
